CREATE TABLE IF NOT EXISTS `users` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) DEFAULT NULL,
  `Email` VARCHAR(50) DEFAULT NULL,
  `FirstName` VARCHAR(255) DEFAULT NULL,
  `LastName` VARCHAR(255) DEFAULT NULL,
  `AvatarUrl` VARCHAR(255) DEFAULT NULL,
  `CreatedBy` VARCHAR(50) NOT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Active` BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (`Id`),
  UNIQUE KEY `UK_Email` (`Email`)
);
