-- Sample data for crm_email table
-- Generated from mockEmails.json
-- This script inserts 10 sample email records for testing and development

USE crm_sys_db;

-- Disable foreign key checks temporarily
SET FOREIGN_KEY_CHECKS = 0;

-- Insert sample email data
INSERT INTO crm_email (
    Id, ConversationId, Subject, BodyPreview, BodyContent, BodyContentType,
    Importance, HasAttachments, IsRead, IsDraft, FromName, FromAddress,
    SenderName, SenderAddress, ToRecipients, CcRecipients, BccRecipients,
    ReplyTo, ReceivedDateTime, SentDateTime, CreatedDateTime,
    LastModifiedDateTime, InternetMessageId, ActivityId,
    CreatedOn, CreatedBy
) VALUES
('AAMkAGI2THVSAAA=', 'AAQkAGI2THVSAAA=',
 'Inquiry about CRM Enterprise Solution for Furniture Business',
 'Hi, I''m interested in learning more about your CRM solution for our furniture manufacturing company. We have about 50 employees and need a comprehensive system to manage customer relationships, inventory tracking, and showroom sales...',
 '<html><body><p>Hi,</p><p>I''m interested in learning more about your CRM solution for our furniture manufacturing company ILVA A/S. We have about 50 employees and need a comprehensive system to manage our customer relationships, inventory tracking, and showroom sales management.</p><p>Could you please send me more information about pricing and features specific to furniture retail operations?</p><p>Best regards,<br>Henrik Kristensen</p></body></html>',
 'html', 'normal', 1, 1, 0,
 'Henrik Kristensen', 'henrik.kristensen@ilva.dk',
 'Henrik Kristensen', 'henrik.kristensen@ilva.dk',
 '[{"name":"Sales Team","address":"sales@crm.com"}]',
 '[{"name":"Henrik Kristensen","address":"henrik.kristensen@ilva.dk"}]',
 '[]', '[]',
 '2025-10-01 08:30:00', '2025-10-01 08:28:00', '2025-10-01 08:28:00', '2025-10-01 08:30:00',
 '<email_001@startupxyz.io>', 1,
 '2025-10-01 08:28:00', 'system@crm.com'),

('AAMkAGI2THVSAAB=', 'AAQkAGI2THVSAAB=',
 'Re: CRM Upgrade Proposal - Final Terms',
 'Thank you for the detailed proposal. We''ve reviewed it with our team and have a few questions about the implementation timeline...',
 '<html><body><p>Dear Sales Team,</p><p>Thank you for the detailed proposal for our furniture logistics and distribution operations. We''ve reviewed it with our team and have a few questions about the implementation timeline.</p><ul><li>Can we start the implementation in Q4 2025?</li><li>What is the training schedule for our warehouse and delivery staff?</li><li>Do you provide on-site support for furniture logistics operations?</li></ul><p>Looking forward to your response.</p><p>Best regards,<br>Minh Phạm<br>Operations Director<br>Response Vietnam Co., Ltd.</p></body></html>',
 'html', 'high', 0, 1, 0,
 'Minh Phạm', 'minh.pham@responsevietnam.com',
 'Minh Phạm', 'minh.pham@responsevietnam.com',
 '[{"name":"Sales Team","address":"sales@crm.com"}]',
 '[{"name":"Technical Support","address":"support@crm.com"}]',
 '[]', '[]',
 '2025-10-03 14:20:00', '2025-10-03 14:15:00', '2025-10-03 14:15:00', '2025-10-03 14:20:00',
 '<email_002@responsevietnam.com>', 3,
 '2025-10-03 14:15:00', 'sales@crm.com'),

('AAMkAGI2THVSBBB=', 'AAQkAGI2THVSBBB=',
 'Meeting Confirmation - Product Demo Tomorrow',
 'This is to confirm our product demo meeting scheduled for tomorrow at 2:00 PM CET...',
 '<html><body><p>Dear Henrik,</p><p>This is to confirm our product demo meeting scheduled for tomorrow at 2:00 PM CET.</p><p><strong>Meeting Details:</strong><br>Topic: CRM Enterprise Solution Demo<br>Date: October 2, 2025<br>Time: 2:00 PM CET<br>Duration: 1 hour<br>Location: Microsoft Teams</p><p>Agenda:<br>1. Product overview<br>2. Feature demonstration<br>3. Q&A session</p><p>Please let us know if you have any questions in advance.</p><p>Best regards,<br>Sales Team</p></body></html>',
 'html', 'normal', 1, 0, 0,
 'Sales Team', 'sales@crm.com',
 'Sales Team', 'sales@crm.com',
 '[{"name":"Henrik Kristensen","address":"henrik.kristensen@ilva.dk"}]',
 '[]', '[]', '[]',
 '2025-10-01 16:45:00', '2025-10-01 16:40:00', '2025-10-01 16:40:00', '2025-10-01 16:45:00',
 '<meeting_confirm_001@crm.com>', 5,
 '2025-10-01 16:40:00', 'sales@crm.com'),

('AAMkAGI2THVSCCC=', 'AAQkAGI2THVSCCC=',
 'Contract Signed - Welcome to CRM Enterprise!',
 'Congratulations! Your contract has been signed and processed. Welcome to the CRM Enterprise family...',
 '<html><body><p>Dear Henrik,</p><p>Congratulations! Your contract has been signed and processed successfully.</p><p><strong>Next Steps:</strong></p><ul><li>Implementation kickoff meeting: October 5, 2025</li><li>System setup: October 6-7, 2025</li><li>User training: October 8-9, 2025</li><li>Go-live: October 10, 2025</li></ul><p>Your account manager will contact you shortly to schedule the implementation details.</p><p>Welcome to the CRM Enterprise family!</p><p>Best regards,<br>Implementation Team</p></body></html>',
 'html', 'high', 1, 0, 0,
 'Implementation Team', 'implementation@crm.com',
 'Implementation Team', 'implementation@crm.com',
 '[{"name":"Henrik Kristensen","address":"henrik.kristensen@ilva.dk"}]',
 '[{"name":"Sales Team","address":"sales@crm.com"}]',
 '[]', '[]',
 '2025-10-02 17:00:00', '2025-10-02 16:55:00', '2025-10-02 16:55:00', '2025-10-02 17:00:00',
 '<contract_signed_001@crm.com>', 6,
 '2025-10-02 16:55:00', 'sales@crm.com'),

('AAMkAGI2THVSDDD=', 'AAQkAGI2THVSDDD=',
 'Design Process Automation - Proposal Review',
 'Thank you for the design process automation proposal. We''ve reviewed it and would like to schedule a follow-up call...',
 '<html><body><p>Dear Sales Team,</p><p>Thank you for the design process automation proposal. Our design team has reviewed it and we''re very interested in the workflow automation features.</p><p>We would like to schedule a follow-up call to discuss:</p><ul><li>Custom workflow configuration</li><li>Integration with our existing design tools</li><li>Pricing for the professional package</li></ul><p>Please suggest some available time slots for next week.</p><p>Best regards,<br>Anders Hejgaard<br>Design Director<br>Hugga Design</p></body></html>',
 'html', 'normal', 0, 1, 0,
 'Anders Hejgaard', 'anders.hejgaard@huggadesign.com',
 'Anders Hejgaard', 'anders.hejgaard@huggadesign.com',
 '[{"name":"Sales Team","address":"sales@crm.com"}]',
 '[]', '[]', '[]',
 '2025-09-29 10:30:00', '2025-09-29 10:25:00', '2025-09-29 10:25:00', '2025-09-29 10:30:00',
 '<proposal_review_001@huggadesign.com>', NULL,
 '2025-09-29 10:25:00', 'sales@crm.com'),

('AAMkAGI2THVSEEE=', 'AAQkAGI2THVSEEE=',
 'Procurement Integration Requirements',
 'We''d like to explore CRM integration possibilities for our procurement and supplier management processes...',
 '<html><body><p>Hello,</p><p>We are John Lewis PLC, a major UK retailer. We''d like to explore CRM integration possibilities for our procurement and supplier management processes.</p><p>Our requirements include:</p><ul><li>Supplier onboarding workflows</li><li>Purchase order management</li><li>Supplier performance tracking</li><li>Compliance reporting</li></ul><p>Could you please provide more information about your procurement integration capabilities?</p><p>Best regards,<br>Alice Forbes<br>Procurement Manager<br>John Lewis PLC</p></body></html>',
 'html', 'normal', 0, 1, 0,
 'Alice Forbes', 'alice.forbes@johnlewis.com',
 'Alice Forbes', 'alice.forbes@johnlewis.com',
 '[{"name":"Sales Team","address":"sales@crm.com"}]',
 '[{"name":"Business Development","address":"bd@crm.com"}]',
 '[]', '[]',
 '2025-09-27 15:45:00', '2025-09-27 15:40:00', '2025-09-27 15:40:00', '2025-09-27 15:45:00',
 '<procurement_inquiry_001@johnlewis.com>', NULL,
 '2025-09-27 15:40:00', 'sales@crm.com'),

('AAMkAGI2THVSFFF=', 'AAQkAGI2THVSFFF=',
 'Taiwan Localization Features - Additional Questions',
 'We have some additional questions about the Mandarin localization and Taiwan-specific features...',
 '<html><body><p>Dear Sales Team,</p><p>Thank you for the detailed information about Taiwan localization. We have some additional questions:</p><ol><li>How do you handle Traditional Chinese character encoding?</li><li>Are there Taiwan-specific payment integrations (like Taiwan Pay)?</li><li>What is the process for localizing custom fields?</li><li>Do you provide documentation in Traditional Chinese?</li></ol><p>We''re very interested in proceeding with the localization package.</p><p>Best regards,<br>Frank Hsia<br>Import Manager<br>Mr Living CO. LTD</p></body></html>',
 'html', 'normal', 0, 1, 0,
 'Frank Hsia', 'contact@mrliving.com.tw',
 'Frank Hsia', 'contact@mrliving.com.tw',
 '[{"name":"Sales Team","address":"sales@crm.com"}]',
 '[]', '[]', '[]',
 '2025-09-14 11:20:00', '2025-09-14 11:15:00', '2025-09-14 11:15:00', '2025-09-14 11:20:00',
 '<taiwan_questions_001@mrliving.com.tw>', NULL,
 '2025-09-14 11:15:00', 'sales@crm.com'),

('AAMkAGI2THVSGGG=', 'AAQkAGI2THVSGGG=',
 'Analytics Module - Feature Comparison',
 'Could you provide a comparison between your analytics module and other solutions we''ve been considering?',
 '<html><body><p>Hello,</p><p>We''re currently evaluating different analytics solutions for our CRM system. Could you provide a feature comparison between your analytics module and the following competitors:</p><ul><li>Salesforce Einstein</li><li>HubSpot Analytics</li><li>Zoho Analytics</li></ul><p>Specifically, we''re interested in:</p><ul><li>Real-time reporting capabilities</li><li>Custom dashboard creation</li><li>Data visualization options</li><li>Integration with existing BI tools</li></ul><p>Thank you for your assistance.</p><p>Best regards,<br>Henrik Kristensen<br>Sales Responsible<br>ILVA A/S</p></body></html>',
 'html', 'normal', 0, 1, 0,
 'Henrik Kristensen', 'henrik.kristensen@ilva.dk',
 'Henrik Kristensen', 'henrik.kristensen@ilva.dk',
 '[{"name":"Sales Team","address":"sales@crm.com"}]',
 '[]', '[]', '[]',
 '2025-10-06 13:10:00', '2025-10-06 13:05:00', '2025-10-06 13:05:00', '2025-10-06 13:10:00',
 '<analytics_comparison_001@ilva.dk>', NULL,
 '2025-10-06 13:05:00', 'sales@crm.com'),

('AAMkAGI2THVSHHH=', 'AAQkAGI2THVSHHH=',
 'Multi-language Support - Implementation Plan',
 'We need a detailed implementation plan for the multi-language support module...',
 '<html><body><p>Dear Team,</p><p>Following our discussion about multi-language support, we need a detailed implementation plan that includes:</p><ol><li>Supported languages and locales</li><li>Translation workflow</li><li>Custom field localization</li><li>Training for our international teams</li><li>Timeline and milestones</li></ol><p>Please provide this information so we can move forward with the approval process.</p><p>Best regards,<br>Karina Skærlund<br>Import Manager<br>Response Vietnam Co., Ltd.</p></body></html>',
 'html', 'high', 0, 1, 0,
 'Karina Skærlund', 'karina.skaelund@responsevietnam.com',
 'Karina Skærlund', 'karina.skaelund@responsevietnam.com',
 '[{"name":"Sales Team","address":"sales@crm.com"}]',
 '[{"name":"Technical Team","address":"tech@crm.com"}]',
 '[]', '[]',
 '2025-10-04 16:30:00', '2025-10-04 16:25:00', '2025-10-04 16:25:00', '2025-10-04 16:30:00',
 '<multilang_plan_001@responsevietnam.com>', NULL,
 '2025-10-04 16:25:00', 'sales@crm.com'),

('AAMkAGI2THVSIII=', 'AAQkAGI2THVSIII=',
 'Logistics CRM Features - Custom Requirements',
 'We have some specific requirements for logistics and supply chain management that we''d like to discuss...',
 '<html><body><p>Hello,</p><p>We are Khori International, a logistics company based in South Korea. We have some specific requirements for logistics and supply chain management:</p><ul><li>FTA (Free Trade Agreement) document management</li><li>Multi-modal transport tracking</li><li>Customs clearance workflows</li><li>Supplier and carrier performance metrics</li><li>Real-time shipment visibility</li></ul><p>Could we schedule a call to discuss how your CRM can be customized for our logistics operations?</p><p>Best regards,<br>Contact Manager<br>Khori International Inc</p></body></html>',
 'html', 'normal', 0, 1, 0,
 'Contact Manager', 'info@khoriintl.com',
 'Contact Manager', 'info@khoriintl.com',
 '[{"name":"Sales Team","address":"sales@crm.com"}]',
 '[]', '[]', '[]',
 '2025-09-21 09:15:00', '2025-09-21 09:10:00', '2025-09-21 09:10:00', '2025-09-21 09:15:00',
 '<logistics_requirements_001@khoriintl.com>', NULL,
 '2025-09-21 09:10:00', 'sales@crm.com');

-- Re-enable foreign key checks
SET FOREIGN_KEY_CHECKS = 1;

-- Display success message
SELECT 'Sample email data inserted successfully. Total records: 10' AS message;
