using System;

namespace CRMSys.Domain.Dynamics
{
    public class SalesQuotationHeadersV2
    {
        public string? OdataEtag { get; set; }
        public string? DataAreaId { get; set; }
        public string? SalesQuotationNumber { get; set; }
        public string? FiscalDocumentOperationTypeId { get; set; }
        public string? SalesQuotationTemplateName { get; set; }
        public string? InvoiceAddressStreet { get; set; }
        public string? CampaignId { get; set; }
        public string? IsCustomerFinalUser { get; set; }
        public string? SalesQuotationName { get; set; }
        public string? Email { get; set; }
        public string? DefaultShippingSiteId { get; set; }
        public string? DeliveryAddressDescription { get; set; }
        public string? IsInvoiceAddressPrivate { get; set; }
        public string? SalesQuotationTypeId { get; set; }
        public string? QuotationDocumentIntroductionName { get; set; }
        public string? QuotationResponsiblePersonnelNumber { get; set; }
        public string? GeneratedSalesOrderNumber { get; set; }
        public string? TeleMarketingCallListId { get; set; }
        public string? NumberSequenceGroupId { get; set; }
        public string? SalesOrderOriginCode { get; set; }
        public decimal? InvoiceAddressLatitude { get; set; }
        public string? CustomerPaymentFinancialInterestCode { get; set; }
        public string? InvoiceAddressStreetInKana { get; set; }
        public decimal? CashDiscountPercentage { get; set; }
        public string? SalesOrderPoolId { get; set; }
        public string? DeliveryAddressCountryRegionId { get; set; }
        public decimal? DeliveryAddressLatitude { get; set; }
        public string? TotalDiscountCustomerGroupCode { get; set; }
        public string? DeliveryAddressCity { get; set; }
        public string? RequestingCustomerAccountNumber { get; set; }
        public string? SalesOrderPromisingMethod { get; set; }
        public decimal? TotalDiscountPercentage { get; set; }
        public string? DeliveryAddressDistrictName { get; set; }
        public string? DeliveryAddressCountyId { get; set; }
        public string? DeliveryAddressZipCode { get; set; }
        public DateTime? SalesQuotationExpiryDate { get; set; }
        public string? SkipOpportunityCreationPrompt { get; set; }
        public string? LanguageId { get; set; }
        public string? DeliveryAddressDunsNumber { get; set; }
        public string? MultilineDiscountCustomerGroupCode { get; set; }
        public string? BankDocumentType { get; set; }
        public string? InvoiceAddressStateId { get; set; }
        public DateTime? SalesQuotationFollowUpDate { get; set; }
        public string? CustomerPaymentMethodSpecificationName { get; set; }
        public string? CommissionCustomerGroupId { get; set; }
        public string? DeliveryAddressName { get; set; }
        public string? QuotationFollowUpActivity { get; set; }
        public string? QuotationReasonCode { get; set; }
        public decimal? QuotationTotalTaxAmount { get; set; }
        public string? InvoiceAddressCountryRegionId { get; set; }
        public string? DeliveryAddressStreetNumber { get; set; }
        public string? DeliveryAddressStreetInKana { get; set; }
        public string? QuotationDocumentTitleName { get; set; }
        public string? ChargeCustomerGroupId { get; set; }
        public string? InvoiceAddressStreetNumber { get; set; }
        public string? IsDeliveryAddressPrivate { get; set; }
        public string? TaxExemptNumber { get; set; }
        public string? AreTotalsCalculated { get; set; }
        public decimal? TotalDiscountAmount { get; set; }
        public string? FormattedInvoiceAddress { get; set; }
        public string? ExportReason { get; set; }
        public string? DeliveryAddressCountryRegionISOCode { get; set; }
        public string? CashDiscountCode { get; set; }
        public string? InvoiceAddressCountryRegionISOCode { get; set; }
        public string? IntrastatTransactionCode { get; set; }
        public string? URL { get; set; }
        public string? CurrencyCode { get; set; }
        public string? ServiceAgreementId { get; set; }
        public string? ArePricesIncludingSalesTax { get; set; }
        public string? InvoiceCustomerAccountNumber { get; set; }
        public string? DeliveryAddressLocationId { get; set; }
        public string? CommissionSalesRepresentativeGroupId { get; set; }
        public string? CustomerTransactionSettlementType { get; set; }
        public string? InvoiceAddressCityInKana { get; set; }
        public decimal? QuotationTotalDiscountAmount { get; set; }
        public DateTime? ReceiptDateRequested { get; set; }
        public string? IntrastatStatisticsProcedureCode { get; set; }
        public string? ProspectId { get; set; }
        public string? OverrideSalesTax { get; set; }
        public string? DeliveryAddressStreet { get; set; }
        public string? DeliveryModeCode { get; set; }
        public DateTime? FixedDueDate { get; set; }
        public string? SalesTaxGroupCode { get; set; }
        public string? IsDeliveryAddressOrderSpecific { get; set; }
        public string? CustomerRequisitionNumber { get; set; }
        public decimal? InvoiceAddressLongitude { get; set; }
        public string? InvoiceAddressCity { get; set; }
        public string? InvoiceAddressPostBox { get; set; }
        public string? ContactPersonId { get; set; }
        public string? EUSalesListCode { get; set; }
        public string? InvoiceAddressDistrictName { get; set; }
        public string? SalesQuotationStatus { get; set; }
        public decimal? QuotationTotalAmount { get; set; }
        public decimal? QuotationHeaderTaxAmount { get; set; }
        public string? SalesQuotationTemplateGroupId { get; set; }
        public string? IsSalesQuotationTemplateActive { get; set; }
        public string? PaymentTermsName { get; set; }
        public string? DeliveryAddressCityInKana { get; set; }
        public string? CustomerPostingProfileId { get; set; }
        public decimal? DeliveryAddressLongitude { get; set; }
        public string? QuotationDocumentConclusionName { get; set; }
        public string? InvoiceAddressZipCode { get; set; }
        public string? DeliveryTermsCode { get; set; }
        public string? DefaultLedgerDimensionDisplayValue { get; set; }
        public string? DeliveryAddressTimeZone { get; set; }
        public string? DefaultShippingWarehouseId { get; set; }
        public string? QuotationTakerPersonnelNumber { get; set; }
        public string? DeliveryAddressStateId { get; set; }
        public string? SalesQuotationHeaderCreationMethod { get; set; }
        public string? DeliveryBuildingCompliment { get; set; }
        public string? IntrastatTransportModeCode { get; set; }
        public string? CustomersReference { get; set; }
        public string? DeliveryAddressPostBox { get; set; }
        public string? InvoiceAddressTimeZone { get; set; }
        public string? OpportunityId { get; set; }
        public string? InvoiceAddressCountyId { get; set; }
        public decimal? QuotationTotalChargesAmount { get; set; }
        public string? LineDiscountCustomerGroupCode { get; set; }
        public string? IntrastatPortId { get; set; }
        public DateTime? SalesQuotationConfirmationDate { get; set; }
        public string? CustomerPaymentFineCode { get; set; }
        public string? InvoiceBuildingCompliment { get; set; }
        public string? PriceCustomerGroupCode { get; set; }
        public string? DeliveryReasonCode { get; set; }
        public decimal? ReportingCurrencyFixedExchangeRate { get; set; }
        public DateTime? RequestedShippingDate { get; set; }
        public string? OperatingUnitPartyNumber { get; set; }
        public string? CustomerPaymentMethodName { get; set; }
        public string? SalesUnitId { get; set; }
        public string? FormattedDeliveryAddress { get; set; }
        public decimal? FixedExchangeRate { get; set; }
        public string? SkipGlobalUnifiedPricingCalculation { get; set; }
        public string? RSVNIsProspect { get; set; }
        public DateTime? RSVNCreatedDateTime { get; set; }
        public string? RSVNQuotationType { get; set; }
        public string? RSVNCreatedBy { get; set; }
        public DateTime? RSVNRemainQuotationExpiryDate { get; set; }
        public string? RSVNSalesResponsibleName { get; set; }
        public string? RSVNNotes { get; set; }
        public string? RSVNPayTermDesc { get; set; }
        public string? RSVNOrigQuotationId { get; set; }
        public string? RSVNSalesManagerName { get; set; }
        public string? RSVNCustCode { get; set; }
    }
}

