CREATE TABLE IF NOT EXISTS crm_email (
  Id VARCHAR(255) PRIMARY KEY,
  ConversationId VARCHAR(255) NULL,
  Subject VARCHAR(500) NULL,
  BodyPreview TEXT NULL,
  BodyContent TEXT NULL,
  BodyContentType VARCHAR(50) DEFAULT 'text',
  Importance VARCHAR(20) DEFAULT 'normal',
  HasAttachments TINYINT(1) NOT NULL DEFAULT 0,
  IsRead TINYINT(1) NOT NULL DEFAULT 0,
  IsDraft TINYINT(1) NOT NULL DEFAULT 0,
  FromName VARCHAR(255) NULL,
  FromAddress VARCHAR(320) NULL,
  SenderName VARCHAR(255) NULL,
  SenderAddress VARCHAR(320) NULL,
  ToRecipients TEXT NULL,
  CcRecipients TEXT NULL,
  BccRecipients TEXT NULL,
  ReplyTo TEXT NULL,
  ReceivedDateTime DATETIME NULL,
  SentDateTime DATETIME NULL,
  CreatedDateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LastModifiedDateTime DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  InternetMessageId VARCHAR(500) NULL,
  ActivityId BIGINT NULL,
  CreatedOn DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CreatedBy VARCHAR(255) NULL,
  UpdatedOn DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  UpdatedBy VARCHAR(255) NULL,

  INDEX idx_crm_email_conversation_id (ConversationId),
  INDEX idx_crm_email_subject (Subject(100)),
  INDEX idx_crm_email_from_address (FromAddress),
  INDEX idx_crm_email_sender_address (SenderAddress),
  INDEX idx_crm_email_is_read (IsRead),
  INDEX idx_crm_email_is_draft (IsDraft),
  INDEX idx_crm_email_received_date_time (ReceivedDateTime),
  INDEX idx_crm_email_sent_date_time (SentDateTime),
  INDEX idx_crm_email_activity_id (ActivityId),
  INDEX idx_crm_email_created_on (CreatedOn),

  FOREIGN KEY (ActivityId) REFERENCES crm_activity(Id) ON DELETE SET NULL
);
